src/Entity/Restaurant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RestaurantRepository")
 */
class Restaurant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City", inversedBy="restaurants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RestaurantPicture", mappedBy="restaurant", orphanRemoval=true)
     */
    private $restaurantPictures;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Feedback", mappedBy="restaurant", orphanRemoval=true)
     */
    private $feedbacks;

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function getAverageRating() : float
{

    $sum = 0;
    $total = 0;
  
   

    foreach($this->getFeedbacks() as $feedback) {
        $sum += $feedback->getRating();
        $total++;
    }
    if ($total > 0) {
        return $sum/$total;
    }

    return 0;
}

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }
public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->restaurantPictures = new ArrayCollection();
        $this->feedbacks = new ArrayCollection();
    }

    /**
     * @return Collection|RestaurantPicture[]
     */
    public function getRestaurantPictures(): Collection
    {
        return $this->restaurantPictures;
    }

    public function addRestaurantPicture(RestaurantPicture $restaurantPicture): self
    {
        if (!$this->restaurantPictures->contains($restaurantPicture)) {
            $this->restaurantPictures[] = $restaurantPicture;
            $restaurantPicture->setRestaurant($this);
        }

        return $this;
    }

    public function removeRestaurantPicture(RestaurantPicture $restaurantPicture): self
    {
        if ($this->restaurantPictures->contains($restaurantPicture)) {
            $this->restaurantPictures->removeElement($restaurantPicture);
            // set the owning side to null (unless already changed)
            if ($restaurantPicture->getRestaurant() === $this) {
                $restaurantPicture->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Feedback[]
     */
    public function getFeedbacks(): Collection
    {
        return $this->feedbacks;
    }

    public function addFeedback(Feedback $feedback): self
    {
        if (!$this->feedbacks->contains($feedback)) {
            $this->feedbacks[] = $feedback;
            $feedback->setRestaurant($this);
        }

        return $this;
    }

    public function removeFeedback(Feedback $feedback): self
    {
        if ($this->feedbacks->contains($feedback)) {
            $this->feedbacks->removeElement($feedback);
            // set the owning side to null (unless already changed)
            if ($feedback->getRestaurant() === $this) {
                $feedback->setRestaurant(null);
            }
        }

        return $this;
    }
}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
        <section class="jumbotron text-center">
            {% for restaurant in restaurants %}
                {% if loop.first %}
                    <div class="container">
                        <h1>Notre meilleur restaurant est...</h1>
                        <h2><strong>{{ restaurant.name }} !</strong> <small class="badge badge-danger">{{ restaurant.averageRating | number_format(2, ',') }} sur 5 étoiles !</small></h2>
                        <p class="lead text-muted">
                            {{ restaurant.description }}
                        </p>
                        <p>
                            <a href="#" class="btn btn-dark my-2">Donner un avis !</a>
                        </p>
                    </div>
                {% endif %}
            {% endfor %}
        </section>

        <div class="album py-5 bg-light">
            <div class="container">

                <div class="row">
                    {% for restaurant in restaurants %}
                        {% if not loop.first %}
                            <div class="col-md-4">
                                <div class="card mb-4 shadow-sm">
                                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                                    <div class="card-body">
                                        <p class="card-text">
                                            <h2>{{restaurant.name}}</h2>
                                                <small class="badge badge-danger">{{ restaurant.averageRating | number_format(2, ',') }} sur 5 étoiles !</small>
                                                {{ restaurant.description }}
                                        </p>

                                        <div class="d-flex justify-content-between float-right">
                                            <a href="#" class="btn btn-sm btn-outline-secondary">Donner un avis</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

{% endblock %}